# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Install iOS Simulator Runtime
      run: |
        sudo xcodebuild -runFirstLaunch
        xcrun simctl list runtimes
    
    - name: Build for iOS
      run: xcodebuild build -scheme SnapShield -destination 'generic/platform=iOS' -skipPackagePluginValidation
    
    - name: Build for tvOS
      run: xcodebuild build -scheme SnapShield -destination 'generic/platform=tvOS' -skipPackagePluginValidation
    
    - name: Build for visionOS
      run: xcodebuild build -scheme SnapShield -destination 'generic/platform=visionOS' -skipPackagePluginValidation
