name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ['15.4']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    
    - name: Build Package (iOS)
      run: |
        xcodebuild -scheme SnapShield \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO \
          -skipPackagePluginValidation \
          build
